[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#000000"
font = "sans serif"

[client]
showSidebarNavigation = true

[browser]
gatherUsageStats = false
